### ISSUE TITLE
Facing error while running with Droidbox

### ISSUE THREAD

**Issue by anuj1708** [lynnlyc/droidbot#11]
While install the apk with
`droidbot -a /home/anuj/Desktop/hawkular-android-client/build/outputs/apk/hawkular-android-client-debug.apk  -event dynamic -duration 100 -o droidbot_out`

It says 

INFO:Device:waiting for device
* daemon not running. starting it now on port 5037 *
* daemon started successfully *
Connecting to a device with serialno=.* with a timeout of 60 secs...
Connected to device with serialno=.*
/usr/local/lib/python2.7/dist-packages/com/dtmilano/android/viewclient.py:2601: UserWarning: Running on emulator but no serial number was specified then 'emulator-5554' is used
  warnings.warn("Running on emulator but no serial number was specified then 'emulator-5554' is used")
Actual device serialno=emulator-5554
adb server is out of date.  killing...
* daemon started successfully *
Traceback (most recent call last):
  File "/usr/local/bin/droidbot", line 9, in <module>
    load_entry_point('droidbot==1.0.0a2', 'console_scripts', 'droidbot')()
  File "/home/anuj/droidbot/droidbot/start.py", line 76, in main
    quiet=opts.quiet)
  File "/home/anuj/droidbot/droidbot/droidbot.py", line 46, in __init__
    self.device = Device(device_serial, output_dir=self.output_dir)
  File "/home/anuj/droidbot/droidbot/types.py", line 58, in __init__
    self.get_display_info()
  File "/home/anuj/droidbot/droidbot/types.py", line 235, in get_display_info
    self.display_info = self.get_adb().getDisplayInfo()
  File "/usr/loc
al/lib/python2.7/dist-packages/com/dtmilano/android/adb/adbclient.py", line 414, in getDisplayInfo
    displayInfo = self.getLogicalDisplayInfo()
  File "/usr/local/lib/python2.7/dist-packages/com/dtmilano/android/adb/adbclient.py", line 431, in getLogicalDisplayInfo
    for line in self.shell('dumpsys display').splitlines():
  File "/usr/local/lib/python2.7/dist-packages/com/dtmilano/android/adb/adbclient.py", line 376, in shell
    self.__send('shell:%s' % cmd, checkok=True, reconnect=False)
  File "/usr/local/lib/python2.7/dist-packages/com/dtmilano/android/adb/adbclient.py", line 242, in __send
    self.__checkOk()
  File "/usr/local/lib/python2.7/dist-packages/com/dtmilano/android/adb/adbclient.py", line 285, in __checkOk
    raise RuntimeError("ERROR: %s %s" % (repr(recv), error))

    RuntimeError: ERROR: ''

**Comment by lynnlyc** [comment]
Probably it is due to multiple versions of ADB installed.
Did you install `adb` command using `apt-get install`? If so, just remove it and add the `${ANDROID_SDK}/platform-tools` to your `PATH`.
Hope it helps.

**Comment by anuj1708** [comment]
Thanks. It helped
